---
title: "Gruźlica"
author: "Michał Buszkiewicz"
date: "10 listopada 2016"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
```

Wczytywanie biblioteki EDAWR zawierającej zbiór "tb". Pomijanie pomiarów zawierających brakujące dane.
```{r results='hide', cache=TRUE}
library(EDAWR)
tb_data <- tb[complete.cases(tb), ]
```

Krótkie podsumowanie danych:
```{r}
knitr::kable(summary(tb_data))
```

Liczba zachorowań z podziałem na płeć:
```{r}
by_sex <- group_by(tb_data, sex) %>% summarize(sum(child), sum(adult), sum(elderly))
knitr::kable(by_sex)
```

Wykres liniowy sumarycznej liczby zachorowań z podziałem na grupę wiekową w kolejnych latach:
```{r fig.align='center'}
sums_by_year = function(dataset, country_choice = NA) {
  filtered_dataset = if (is.na(country_choice))
                       dataset
                     else
                       dataset %>% filter(country == country_choice)
  result = filtered_dataset %>%
           group_by(year) %>%
           summarize(
             child = sum(child),
             adult = sum(adult),
             elderly = sum(elderly)
           )
}

plot_tb_data = function(dataset, country = NA) {
  title = if (is.na(country)) "Zachorowania na gruźlicę w grupach wiekowych" else country
  grouped_data = sums_by_year(dataset, country)
  print(length(grouped_data$year))
  matplot(x = grouped_data$year, y = grouped_data %>% select(-year),
          type = c("b"), pch = 1,
          main = title, ylab = "Liczba zachorowań", xlab = "Rok badania")
  legend("topleft", legend=c("Dzieci", "Dorośli", "Starsi"), col = 1:3, pch = 1)
}

plot_tb_data(tb_data)
```

Analogiczne do powyższego wykresy dla poszczególnych krajów:
```{r fig.align='center', results='hide'}

countries = unique(tb_data$country)
for (i in countries) {
  plot_tb_data(tb_data, i)
}
```